#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx3072M
# Silenciar advertencia de compatibilidad de plugins KMP/Android
kotlin.mpp.androidGradlePluginCompatibility.nowarn=true
#Kotlin Native (iOS) - Disable caches temporarily to avoid OutOfMemoryError
kotlin.native.cacheKind=none
kotlin.incremental=true

#Gradle
org.gradle.jvmargs=-Xmx4096M -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.parallel=true

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true
android.defaults.buildfeatures.resvalues=true
android.sdk.defaultTargetSdkToCompileSdkIfUnset=false
android.enableAppCompileTimeRClass=false
android.usesSdkInManifest.disallowed=false
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false
android.r8.optimizedResourceShrinking=false
android.builtInKotlin=false
android.newDsl=false