package com.apptolast.spaindecides.data.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Data class for inserting or updating a vote in Supabase.
 *
 * This model is used for upsert operations on the proposal_votes table.
 * Unlike [ProposalVote], this does not include the `id` field since it's
 * auto-generated by the database.
 *
 * @property proposalId ID of the proposal being voted on
 * @property userId ID of the user casting the vote
 * @property voteType Type of vote: 1 for upvote, -1 for downvote
 */
@Serializable
data class ProposalVoteUpsert(
    @SerialName("proposal_id") val proposalId: String,
    @SerialName("user_id") val userId: String,
    @SerialName("vote_type") val voteType: Int
)